version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    networks:
      - mynetwork
    container_name: backend

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    ports:
      - "8501:8501"
    restart: always
    networks:
      - mynetwork
    container_name: frontend

networks:
  mynetwork:
    driver: bridge
